---
- hosts: localhost
  become: true
  become_user: root
  connection: local
  tasks:
    - name: Update apt repo and cache on Debian/Ubuntu
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
      when: ansible_os_family == 'Debian'

    - name: Upgrade all packages on Debian/Ubuntu
      apt:
        upgrade: safe
        autoremove: yes
        force_apt_get: yes
      when: ansible_os_family == 'Debian'

    - name: Upgrade all packages on RedHat
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'

    # - name: Check if a reboot is needed on all servers
    #   register: reboot_required_file
    #   stat: path=/var/run/reboot-required get_md5=no

    - name: install-packages
      apt:
        name:
          - net-tools
          - apt-transport-https
          - vim
        state: latest
      when: ansible_os_family == 'Debian'

    - name: install-packages
      yum:
        name:
          - vim
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Restart server
      command: /sbin/shutdown -r +2
      async: 0
      poll: 0
      ignore_errors: true
